[package]
name = "arrayfire"
version = "3.0.0"
authors = ["Jason Ramapuram <jason.ramapuram@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "*"
num = "*"
time = "*"

[build-dependencies.rustc-serialize]
rustc-serialize = "*"

[lib]
name = "arrayfire"
path = "src/lib.rs"

[[example]]
name = "helloworld"
path = "examples/helloworld.rs"

[[example]]
name = "pi"
path = "examples/pi.rs"

[[example]]
name = "snow"
path = "examples/snow.rs"

[[example]]
name = "histogram"
path = "examples/histogram.rs"
