[package]
name = "arrayfire"
version = "3.0.0"
authors = ["Jason Ramapuram <jason.ramapuram@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "*"

[build-dependencies.rustc-serialize]
rustc-serialize = "*"

[lib]
name = "arrayfire"
path = "src/lib.rs"

[[test]]
name = "helloworld"
path = "tests/hello_world.rs"
